notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
  path('', views.index, name='index'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('signup/', views.signup, name='signup'),
  path('home/', views.home, name='home'),
  path('note/fav/', views.favourite, name='favourite'),
  path('dashboard/', views.dashboard, name='dashboard'),
  path('profile/', views.profile, name='profile'),
  path('favourites/', views.favourites, name='favourites'),
  path('add/', views.add, name='add'),
  path('note/<slug:slug>/', views.note_detail, name='note_detail'),
  path('search/', views.search, name='search'),
  path('delete/<slug:slug>/', views.delete, name='delete'),
  path('edit/<slug:slug>/', views.edit, name='edit'),
  path('user/<str:username>/', views.user_notes, name='user_notes'),
  path('tag/<slug:slug>/', views.tag, name='tag'),
]

notesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from notes import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('', include('notes.urls', namespace='notes'))
]

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from PIL import Image
from ckeditor_uploader.fields import RichTextUploadingField

# profile model
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  image = models.ImageField(default='profiles/default.jpg', upload_to='profiles')

  def __str__(self):
    return self.user.username
  
  def save(self, *args, **kwargs):
    super().save()

    img = Image.open(self.image.path)
    
    if img.height > 300 or img.width > 300:
      output_size = (300, 300)
      img.thumbnail(output_size)
      img.save(self.image.path)

# notes
class Note(models.Model):
  STATUS_CHOICES = (
    ('public', 'Public'),
    ('private', 'Private')
  )
  title = models.CharField(max_length=120)
  body = RichTextUploadingField()
  attatchment = models.FileField(upload_to='attatchment/', blank=True, null=True)
  date_posted = models.DateTimeField(auto_now_add=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
  status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='private')
  tags = TaggableManager()
  slug = models.SlugField(max_length=250, unique=True)
  favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

  class Meta:
    ordering = ('-date_posted', )

  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    reverse('notes:note_detail', args=[self.slug])

  def favourites(self):
    return [user for user in self.favourite.all()]

def slug_generator(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Note)

notes/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Note, Profile

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

class NoteCreationForm(forms.ModelForm):
  class Meta:
    model = Note
    fields = ['title', 'body', 'attatchment', 'status', 'tags']

class UserUpdateForm(forms.ModelForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email']
  
class ProfileUpdateForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['image']

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import UserRegisterForm, NoteCreationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from .models import Note
from django.utils.html import escape
from django.contrib.auth.models import User
import json

# index.html
def index(request):
  if request.user.is_authenticated:
    return redirect('notes:home')
  return render(request, 'index.html')

# /home
@login_required
def home(request):
  notes = Note.objects.filter(status='public')
  
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': 'All Public Notes'
  })

# /dashboard/
@login_required
def dashboard(request):
  public_notes = Note.objects.filter(author=request.user, status='public')
  private_notes = Note.objects.filter(author=request.user, status='private')

  return render(request, 'notes/dashboard.html', {
    'public_notes': public_notes,
    'private_notes': private_notes
  })

# /search/
@login_required
def search(request):
  notes = []
  if request.method == 'GET':
    search_word = request.GET.get('search')
    if search_word:
      search_word = escape(search_word).lower()

      notes = Note.objects.filter(status='public').filter(body__icontains=search_word).order_by('-date_posted') or Note.objects.filter(status='public').filter(title__icontains=search_word).order_by('-date_posted') or Note.objects.filter(status='public').filter(tags__name__in=[search_word]).distinct().order_by('-date_posted')
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': 'Search Results'
  })

# /delete/<slug:slug>/
@login_required
def delete(request, slug):
  if request.method == 'POST' and slug:
    note = Note.objects.filter(slug=slug).first()
    if note:
      # check if request.user == note.author are same
      if note.author == request.user:
        note.delete()
        messages.success(request, 'Successfully deleted the note!')

  return redirect('notes:home')

# /edit/<slug:slug>/
@login_required
def edit(request, slug):
  note = Note.objects.filter(slug=slug).first()
  # check if request.user == note.author are same
  if note and note.author == request.user:
    # if it is a GET request
    if request.method == 'GET' and slug:
      form = NoteCreationForm(initial={
        'title': note.title,
        'body': note.body,
        'status': note.status,
        'tags': note.tags.all()
      })
      return render(request, 'notes/edit.html', {
        'form': form,
        'note': note
      })
    elif request.method == 'POST':
      form = NoteCreationForm(data=request.POST, instance=note)
      if form.is_valid():
        form.save()
        messages.success(request, 'Note has been updated successfully!')

  return redirect('notes:home')

# /profile/
@login_required
def profile(request):
  if request.method == 'POST':
    user_form = UserUpdateForm(request.POST, instance=request.user)
    profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

    if user_form.is_valid() and profile_form.is_valid():
      user_form.save()
      profile_form.save()
      messages.success(request, 'Your account has been updated successfully!')
      return redirect('notes:profile')
  else:
    user_form = UserUpdateForm(instance=request.user)
    profile_form = ProfileUpdateForm(instance=request.user.profile)
  
  return render(request, 'notes/profile.html', {
    'user_form': user_form,
    'profile_form': profile_form
  })

# /user/<str:username>/
@login_required
def user_notes(request, username):
  notes = []
  user = User.objects.filter(username=username).first()

  if user:
    notes = Note.objects.filter(status='public', author=user)
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': f'{user.username}\'s Notes'
  })

# /tag/<slug:slug>/
@login_required
def tag(request, slug):
  notes = []
  tag = slug
  if request.method == 'GET':
    if tag:
      tag = escape(tag).lower()

      notes = Note.objects.filter(status='public').filter(tags__name__in=[tag]).distinct().order_by('-date_posted') 
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': f'Tag: #{tag}'
  })

# /add/
@login_required
def add(request):
  if request.method == 'POST':
    form = NoteCreationForm(request.POST, request.FILES)
    if form.is_valid():
      instance = form.save(commit=False)
      tags = form.cleaned_data['tags']
      instance.author = request.user
      instance.save()
      for tag in tags:
        instance.tags.add(tag)
      messages.success(request, f'Your Note has been added!')
      return redirect('notes:home')
    else:
      messages.error(request, f'Oops, some error happened, Try Again!')
  else:
    form = NoteCreationForm()
  return render(request, 'notes/add.html', {
    'form': form
  })

# /note/<slug:slug>/
@login_required
def note_detail(request, slug):
  note = get_object_or_404(Note, slug=slug)

  """ if note is private, then the user who added it can only see it """
  if note.status == 'private':
    if not (note.author == request.user):

      return redirect('notes:home')
  
  return render(request, 'notes/detail.html', {
    'note': note
  })

# /favourites/
@login_required
def favourites(request):
  notes = request.user.favourite.all()

  return render(request, 'notes/favourites.html', {
    'notes': notes,
    'title': 'Your Favourites'
  })

# /login/
def login_view(request):
  next_url = request.GET.get('next')

  if request.user.is_authenticated:
    return redirect('notes:home')

  if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      user = form.get_user()
      login(request, user)
      return redirect(next_url) if next_url else redirect('notes:home')
  else:
    form = AuthenticationForm()
  return render(request, 'notes/login.html', {
    'form': form
  })

# /signup/
def signup(request):
  if request.user.is_authenticated:
    return redirect('notes:home')

  if request.method == 'POST':
    form = UserRegisterForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, f'Your Account created successfully!')
      return redirect('notes:login')
  else:
    form = UserRegisterForm()
  return render(request, 'notes/signup.html', {
    'form': form
  })

# /note/fav/<str:id>/
@login_required
def favourite(request):
  if request.method == 'POST':
    id = json.load(request)['id']
    note = get_object_or_404(Note, id=id)
    if note.favourite.filter(id=request.user.id).exists():
      # remove it from favourite
      note.favourite.remove(request.user)
      return JsonResponse({
      'status': 200,
      'msg': 'success',
      'meta': 'Removed from Favourites'
    })
    else:
      note.favourite.add(request.user)
      return JsonResponse({
    'status': 200,
      'msg': 'success',
    'meta': 'Added To Favourites'
  })
  return JsonResponse({
    'status': 400,
    'msg': 'error'
  })

# /logout/
def logout_view(request):
  logout(request)
  return redirect('notes:index')

# 404
def handler404(request, exception):
  return render(request, '404.html', status=404)

# 500
def handler500(request):
  return render(request, '500.html', status=500)

notes/templates/notes/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Add A New Note</title>
{% endblock %}

{% block content %}
  <form action="" method="POST" class="mt-3 mb-4" enctype="multipart/form-data">
    {% csrf_token %}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">
        <h2>Add A New Note</h2>
      </legend>
    </fieldset>
    {{ form.media }} 

    {{ form|crispy }}

    <div class="form-group">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
  
{% endblock %}

notes/templates/notes/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Dashboard</title>
{% endblock %}

{% block content %}
  <h2 class="mb-3">Dashboard</h2>
  <nav class="mb-4">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Public</a>
      <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Private</a>
    
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      {% if public_notes %}
      <div class="custom-cards">
        {% for note in public_notes %}
        <div class="custom-card">
          <div class="custom-card__top border-bottom">
            <div class="custom-card__author">
              <a href="{% url 'notes:user_notes' note.author.username  %}">
                <img src="{{ note.author.profile.image.url }}" alt="avatar" class="avatar-sm">
                <span class="name">{{ note.author.username }}</span>
              </a>
              
            </div>
            {% if note.author == user %}
              <a href="{% url 'notes:edit' note.slug %}" class="text-muted">
                Edit
              </a>
             
            {% endif %}
          </div>
          <div class="custom-card__middle">
            <h5 class="custom-card__title">
              <a href="{% url 'notes:note_detail' note.slug %}">
                {{ note.title }}
              </a>
              {% if note.attatchment %}
              <div class="attatchment">
                <a href="{{ note.attatchment.url }}" download>
                  <i data-toggle="tooltip" data-placement="bottom" title="Attatchment" class='bx bxs-file' ></i></a>
              </div>
            {% endif %}
            </h5>
           
            <p class="tags">{% for tag in note.tags.all %}
              <small><a href="{% url 'notes:tag' tag.slug %}" class="text-muted">#{{ tag.slug }}</a></small>
              {% endfor %}</p>
          </div>
          
          <div class="custom-card__bottom">
            <small class="text-muted">{{ note.date_posted|date:"m/j/o" }}</small>
              {% if note in user.favourite.all %}
              <button data-id="{{ note.id }}" type="button" class="fav_btn fav">
                <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
              </button>
              {% else %}
              <button data-id="{{ note.id }}" type="button" class="fav_btn">
                <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
              </button>
              {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
        <p>You haven't added any public notes!</p>
      {% endif %}
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      {% if private_notes %}
      <div class="custom-cards">
        {% for note in private_notes %}
        <div class="custom-card">
          <div class="custom-card__top border-bottom">
            <div class="custom-card__author">
              <a href="{% url 'notes:user_notes' note.author.username  %}">
                <img src="{{ note.author.profile.image.url }}" alt="avatar" class="avatar-sm">
                <span class="name">{{ note.author.username }}</span>
              </a>
              
            </div>
            {% if note.author == user %}
              <a href="{% url 'notes:edit' note.slug %}" class="text-muted">
                Edit
              </a>
             
            {% endif %}
          </div>
          <div class="custom-card__middle">
            <h5 class="custom-card__title">
              <a href="{% url 'notes:note_detail' note.slug %}">
                {{ note.title }}
              </a>
              {% if note.attatchment %}
              <div class="attatchment">
                <a href="{{ note.attatchment.url }}" download>
                  <i data-toggle="tooltip" data-placement="bottom" title="Attatchment" class='bx bxs-file' ></i></a>
              </div>
            {% endif %}
            </h5>
            
            <p class="tags"><small>Tags:</small>{% for tag in note.tags.all %}
              <small><a href="{% url 'notes:tag' tag.slug %}" class="text-muted">#{{ tag.slug }}</a></small>
              {% endfor %}</p>
          </div>
          
          <div class="custom-card__bottom">
            <small class="text-muted">{{ note.date_posted|date:"m/j/o" }}</small>
              {% if note in user.favourite.all %}
              <button data-id="{{ note.id }}" type="button" class="fav_btn fav">
                <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
              </button>
              {% else %}
              <button data-id="{{ note.id }}" type="button" class="fav_btn">
                <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
              </button>
              {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
        <p>You haven't added any private notes!</p>
      {% endif %}
    </div>
  </div>
{% endblock %}
{% block script %}
<script defer type="text/javascript" src="{% static 'js/fav.js' %}"></script>
{% endblock %}

notes/templates/notes/detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ note.title }}</title>
{% endblock %}

{% block content %}
  <div class="notes__detail__page mb-5">
    <div class="notes__detail--top">
      <h1>{{note.title}}</h1>
      {% if note.author == user %}
        <form action="{% url 'notes:delete' note.slug %}" method="POST">
          {% csrf_token %}
          <!-- Button trigger modal -->
        <div class="d-flex">
          <a href="{% url 'notes:edit' note.slug %}" class="btn btn-primary mx-2">Edit</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
          Delete
        </button>
      </div>

  
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 99999999999999;">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this?</h5>
              
                <span style="cursor: pointer; font-size: 1.2rem;" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</span>
            
            </div>
            
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  
              <button type="submit" class="btn btn-danger">Delete</button>
            </div>
          </div>
        </div>
      </div>
          
        </form>
      {% endif %}
    </div>
    <div class="notes__detail__extras">
      <span class="name text-muted">Posted by {{ note.author.username }} on {{ note.date_posted|date:"m/j/o" }}</span>
    </div>
    <p class="note__detail__tags tags mb-5">
      <small>Tags:</small> {% for tag in note.tags.all %}
      <small><a href="{% url 'notes:tag' tag.slug %}" class="text-muted">#{{ tag }}</a></small>
      {% endfor %}</p>
    {% if note.attatchment %}
      <div class="attatchment">
        <a href="{{ note.attatchment.url }}" download>
          <i class='bx bxs-file' ></i>{{ note.attatchment.name|truncatechars:40 }}</a>
      </div>
    {% endif %}
    <div class="notes__detail">
      {{ note.body|safe }}
    </div>
  </div>
{% endblock %}

notes/templates/notes/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Edit Note</title>
{% endblock %}

{% block content %}
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 99999999999999;">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this?</h5>
              
                <span style="cursor: pointer; font-size: 1.2rem;" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</span>
            
            </div>
            
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  
              <form action="{% url 'notes:delete' note.slug %}" method="POST">
                {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
        </form>

            </div>
          </div>
        </div>
      </div>
          
  <form action="" method="POST" class="mt-3 mb-4">
    {% csrf_token %}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">
        <h2>Edit Note</h2>
      </legend>
    </fieldset>
    {{ form.media }} 

    {{ form|crispy }}

    <div class="form-group">
      <button type="submit" class="btn btn-success">Save</button>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        Delete
      </button>
    </div>
  </form>
  
{% endblock %}

notes/templates/notes/favourites.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Favourites</title>
{% endblock %}

{% block content %}
<h2 class="mb-4">{{ title }}</h2>


  {% if notes %}
    <div class="custom-cards">
      {% for note in notes %}
      <div class="custom-card">
        <div class="custom-card__top border-bottom">
          <div class="custom-card__author">
            <a href="{% url 'notes:user_notes' note.author.username  %}">
              <img src="{{ note.author.profile.image.url }}" alt="avatar" class="avatar-sm">
              <span class="name">{{ note.author.username }}</span>
            </a>
            
          </div>
          {% if note.author == user %}
            <a href="{% url 'notes:edit' note.slug %}" class="text-muted">
              Edit
            </a>
           
          {% endif %}
        </div>
        <div class="custom-card__middle">
          <h5 class="custom-card__title">
            <a href="{% url 'notes:note_detail' note.slug %}">
              {{ note.title }}
            </a>
            {% if note.attatchment %}
              <div class="attatchment">
                <a href="{{ note.attatchment.url }}" download>
                  <i data-toggle="tooltip" data-placement="bottom" title="Attatchment" class='bx bxs-file' ></i></a>
              </div>
            {% endif %}
          </h5>
          <p class="tags"><small>Tags:</small>{% for tag in note.tags.all %}
            <small><a href="{% url 'notes:tag' tag.slug %}" class="text-muted">#{{ tag.slug }}</a></small>
            {% endfor %}</p>
        </div>
        
        <div class="custom-card__bottom">
          <small class="text-muted">{{ note.date_posted|date:"m/j/o" }}</small>
            {% if note in user.favourite.all %}
            <button data-id="{{ note.id }}" type="button" class="fav_btn fav">
              <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
            </button>
            {% else %}
            <button data-id="{{ note.id }}" type="button" class="fav_btn">
              <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
            </button>
            {% endif %}
        </div>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <p>You didn't have any Favourites!</p>
  {% endif %}
{% endblock %}
{% block script %}
<script defer type="text/javascript" src="{% static 'js/fav.js' %}"></script>
{% endblock %}

notes/templates/notes/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Home</title>
{% endblock %}

{% block content %}
<h2 class="mb-4">{{ title }}</h2>

  <form class="searchbox mb-4" role="search" method="GET" action="{% url 'notes:search' %}">
      <i class='bx bx-search-alt text-muted'></i>
      <input type="text" name="search" placeholder="Search public notes..." >
    
  </form>
  {% if notes %}
    <div class="custom-cards">
      {% for note in notes %}
      <div class="custom-card">
        <div class="custom-card__top border-bottom">
          <div class="custom-card__author">
            <a href="{% url 'notes:user_notes' note.author.username  %}">
              <img src="{{ note.author.profile.image.url }}" alt="avatar" class="avatar-sm">
              <span class="name">{{ note.author.username }}</span>
            </a>
            
          </div>
          {% if note.author == user %}
            <a href="{% url 'notes:edit' note.slug %}" class="text-muted">
              Edit
            </a>
           
          {% endif %}
        </div>
        <div class="custom-card__middle">
          <h5 class="custom-card__title">
            <a href="{% url 'notes:note_detail' note.slug %}">
              {{ note.title }}
            </a>
            {% if note.attatchment %}
              <div class="attatchment">
                <a href="{{ note.attatchment.url }}" download>
                  <i data-toggle="tooltip" data-placement="bottom" title="Attatchment" class='bx bxs-file' ></i></a>
              </div>
            {% endif %}
          </h5>
       
          <p class="tags"><small>Tags:</small>{% for tag in note.tags.all %}
            <small><a href="{% url 'notes:tag' tag.slug %}" class="text-muted">#{{ tag.slug }}</a></small>
            {% endfor %}</p>
        </div>
        
        <div class="custom-card__bottom">
          <small class="text-muted">{{ note.date_posted|date:"m/j/o" }}</small>
            {% if note in user.favourite.all %}
            <button data-id="{{ note.id }}" type="button" class="fav_btn fav">
              <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
            </button>
            {% else %}
            <button data-id="{{ note.id }}" type="button" class="fav_btn">
              <i data-toggle="tooltip" data-placement="bottom" title="Add To Favourites" class='bx bx-heart-circle'></i>
            </button>
            {% endif %}
        </div>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <p>Oops, no Notes Found!</p>
  {% endif %}
{% endblock %}
{% block script %}
<script defer type="text/javascript" src="{% static 'js/fav.js' %}"></script>
{% endblock %}

notes/templates/notes/login.html
{% extends 'base_auth.html' %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Login</title>
{% endblock %}

{% block content %}
  <form action="" method="POST" class="auth--form">
    {% csrf_token %}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>
    </fieldset>
    {{ form|crispy }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Login</button>
    </div>
  </form>
  <div class="pt-3">
    <small class="text-muted">
      Don't have an Account? <a href="{% url 'notes:signup' %}" class="ml-2">Sign Up</a>
    </small>
  </div>
{% endblock %}

notes/templates/notes/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Edit Your Profile</title>
{% endblock %}

{% block content %}
<div class="update_form mb-4">
  <div class="content-section">
    <div class="media">
      <img src="{{ user.profile.image.url }}" alt="profile" class="rounded-circle account-img">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email|truncatechars:15 }}</p>
      </div>
    </div>
  </div>
    <form action="" method="POST"  enctype="multipart/form-data">
      {% csrf_token %}
      
  
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Edit Your Profile</legend>
      </fieldset>
      {{ user_form|crispy }}
      {{ profile_form|crispy }}
  
      <div class="form-group">
        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </form>
</div>
  
{% endblock %}

notes/templates/notes/signup.html
{% extends 'base_auth.html' %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Signup</title>
{% endblock %}

{% block content %}
  <form action="" method="POST" class="auth--form">
    {% csrf_token %}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Sign Up</legend>
    </fieldset>
    {{ form|crispy }}

    <div class="form-group">
      <button type="submit" class="btn btn-success">Sign Up</button>
    </div>
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">
      Already Have an Account? <a href="{% url 'notes:login' %}" class="ml-2">Login</a>
    </small>
  </div>
{% endblock %}