notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
  path('', views.index, name='index'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('signup/', views.signup, name='signup'),
  path('home/', views.home, name='home'),
  path('note/fav/', views.favourite, name='favourite'),
  path('dashboard/', views.dashboard, name='dashboard'),
  path('profile/', views.profile, name='profile'),
  path('favourites/', views.favourites, name='favourites'),
  path('add/', views.add, name='add'),
  path('note/<slug:slug>/', views.note_detail, name='note_detail'),
  path('search/', views.search, name='search'),
  path('delete/<slug:slug>/', views.delete, name='delete'),
  path('edit/<slug:slug>/', views.edit, name='edit'),
  path('user/<str:username>/', views.user_notes, name='user_notes'),
  path('tag/<slug:slug>/', views.tag, name='tag'),
]

notesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from notes import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('', include('notes.urls', namespace='notes'))
]

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from django.db.models.signals import pre_save
from .utils import unique_slug_generator
from PIL import Image
from ckeditor_uploader.fields import RichTextUploadingField

# profile model
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  image = models.ImageField(default='profiles/default.jpg', upload_to='profiles')

  def __str__(self):
    return self.user.username
  
  def save(self, *args, **kwargs):
    super().save()

    img = Image.open(self.image.path)
    
    if img.height > 300 or img.width > 300:
      output_size = (300, 300)
      img.thumbnail(output_size)
      img.save(self.image.path)

# notes
class Note(models.Model):
  STATUS_CHOICES = (
    ('public', 'Public'),
    ('private', 'Private')
  )
  title = models.CharField(max_length=120)
  body = RichTextUploadingField()
  attatchment = models.FileField(upload_to='attatchment/', blank=True, null=True)
  date_posted = models.DateTimeField(auto_now_add=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
  status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='private')
  tags = TaggableManager()
  slug = models.SlugField(max_length=250, unique=True)
  favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

  class Meta:
    ordering = ('-date_posted', )

  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    reverse('notes:note_detail', args=[self.slug])

  def favourites(self):
    return [user for user in self.favourite.all()]

def slug_generator(sender, instance, *args, **kwargs):
  if not instance.slug:
    instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Note)

notes/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Note, Profile

class UserRegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

class NoteCreationForm(forms.ModelForm):
  class Meta:
    model = Note
    fields = ['title', 'body', 'attatchment', 'status', 'tags']

class UserUpdateForm(forms.ModelForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email']
  
class ProfileUpdateForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['image']

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import UserRegisterForm, NoteCreationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from .models import Note
from django.utils.html import escape
from django.contrib.auth.models import User
import json

# index.html
def index(request):
  if request.user.is_authenticated:
    return redirect('notes:home')
  return render(request, 'index.html')

# /home
@login_required
def home(request):
  notes = Note.objects.filter(status='public')
  
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': 'All Public Notes'
  })

# /dashboard/
@login_required
def dashboard(request):
  public_notes = Note.objects.filter(author=request.user, status='public')
  private_notes = Note.objects.filter(author=request.user, status='private')

  return render(request, 'notes/dashboard.html', {
    'public_notes': public_notes,
    'private_notes': private_notes
  })

# /search/
@login_required
def search(request):
  notes = []
  if request.method == 'GET':
    search_word = request.GET.get('search')
    if search_word:
      search_word = escape(search_word).lower()

      notes = Note.objects.filter(status='public').filter(body__icontains=search_word).order_by('-date_posted') or Note.objects.filter(status='public').filter(title__icontains=search_word).order_by('-date_posted') or Note.objects.filter(status='public').filter(tags__name__in=[search_word]).distinct().order_by('-date_posted')
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': 'Search Results'
  })

# /delete/<slug:slug>/
@login_required
def delete(request, slug):
  if request.method == 'POST' and slug:
    note = Note.objects.filter(slug=slug).first()
    if note:
      # check if request.user == note.author are same
      if note.author == request.user:
        note.delete()
        messages.success(request, 'Successfully deleted the note!')

  return redirect('notes:home')

# /edit/<slug:slug>/
@login_required
def edit(request, slug):
  note = Note.objects.filter(slug=slug).first()
  # check if request.user == note.author are same
  if note and note.author == request.user:
    # if it is a GET request
    if request.method == 'GET' and slug:
      form = NoteCreationForm(initial={
        'title': note.title,
        'body': note.body,
        'status': note.status,
        'tags': note.tags.all()
      })
      return render(request, 'notes/edit.html', {
        'form': form,
        'note': note
      })
    elif request.method == 'POST':
      form = NoteCreationForm(data=request.POST, instance=note)
      if form.is_valid():
        form.save()
        messages.success(request, 'Note has been updated successfully!')

  return redirect('notes:home')

# /profile/
@login_required
def profile(request):
  if request.method == 'POST':
    user_form = UserUpdateForm(request.POST, instance=request.user)
    profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

    if user_form.is_valid() and profile_form.is_valid():
      user_form.save()
      profile_form.save()
      messages.success(request, 'Your account has been updated successfully!')
      return redirect('notes:profile')
  else:
    user_form = UserUpdateForm(instance=request.user)
    profile_form = ProfileUpdateForm(instance=request.user.profile)
  
  return render(request, 'notes/profile.html', {
    'user_form': user_form,
    'profile_form': profile_form
  })

# /user/<str:username>/
@login_required
def user_notes(request, username):
  notes = []
  user = User.objects.filter(username=username).first()

  if user:
    notes = Note.objects.filter(status='public', author=user)
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': f'{user.username}\'s Notes'
  })

# /tag/<slug:slug>/
@login_required
def tag(request, slug):
  notes = []
  tag = slug
  if request.method == 'GET':
    if tag:
      tag = escape(tag).lower()

      notes = Note.objects.filter(status='public').filter(tags__name__in=[tag]).distinct().order_by('-date_posted') 
  return render(request, 'notes/index.html', {
    'notes': notes,
    'title': f'Tag: #{tag}'
  })

# /add/
@login_required
def add(request):
  if request.method == 'POST':
    form = NoteCreationForm(request.POST, request.FILES)
    if form.is_valid():
      instance = form.save(commit=False)
      tags = form.cleaned_data['tags']
      instance.author = request.user
      instance.save()
      for tag in tags:
        instance.tags.add(tag)
      messages.success(request, f'Your Note has been added!')
      return redirect('notes:home')
    else:
      messages.error(request, f'Oops, some error happened, Try Again!')
  else:
    form = NoteCreationForm()
  return render(request, 'notes/add.html', {
    'form': form
  })

# /note/<slug:slug>/
@login_required
def note_detail(request, slug):
  note = get_object_or_404(Note, slug=slug)

  """ if note is private, then the user who added it can only see it """
  if note.status == 'private':
    if not (note.author == request.user):

      return redirect('notes:home')
  
  return render(request, 'notes/detail.html', {
    'note': note
  })

# /favourites/
@login_required
def favourites(request):
  notes = request.user.favourite.all()

  return render(request, 'notes/favourites.html', {
    'notes': notes,
    'title': 'Your Favourites'
  })

# /login/
def login_view(request):
  next_url = request.GET.get('next')

  if request.user.is_authenticated:
    return redirect('notes:home')

  if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      user = form.get_user()
      login(request, user)
      return redirect(next_url) if next_url else redirect('notes:home')
  else:
    form = AuthenticationForm()
  return render(request, 'notes/login.html', {
    'form': form
  })

# /signup/
def signup(request):
  if request.user.is_authenticated:
    return redirect('notes:home')

  if request.method == 'POST':
    form = UserRegisterForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, f'Your Account created successfully!')
      return redirect('notes:login')
  else:
    form = UserRegisterForm()
  return render(request, 'notes/signup.html', {
    'form': form
  })

# /note/fav/<str:id>/
@login_required
def favourite(request):
  if request.method == 'POST':
    id = json.load(request)['id']
    note = get_object_or_404(Note, id=id)
    if note.favourite.filter(id=request.user.id).exists():
      # remove it from favourite
      note.favourite.remove(request.user)
      return JsonResponse({
      'status': 200,
      'msg': 'success',
      'meta': 'Removed from Favourites'
    })
    else:
      note.favourite.add(request.user)
      return JsonResponse({
    'status': 200,
      'msg': 'success',
    'meta': 'Added To Favourites'
  })
  return JsonResponse({
    'status': 400,
    'msg': 'error'
  })

# /logout/
def logout_view(request):
  logout(request)
  return redirect('notes:index')

# 404
def handler404(request, exception):
  return render(request, '404.html', status=404)

# 500
def handler500(request):
  return render(request, '500.html', status=500)

notes/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
  <link rel="icon" href="{% static 'favicon.png' %}" sizes="16x16" type="image/png" />
  {% block title %} {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

  <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css" />
  <!-- highlight.js-->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- highlight.js -->
</head>

<body class="hide">
  <div class="wrapper">
    <nav class="sidebar">
      <div class="sidebar__top">
        <div class="brand">
          <i class='bx bx-note icon'></i>
          <span class="brand__name">NOTESAPP</span>
        </div>



        <a href="{% url 'notes:home' %}" class="sidebar__link">
          <i class='bx bx-home-circle icon'></i>
          <span class="text">Home</span>
        </a>
        <a href="{% url 'notes:dashboard' %}" class="sidebar__link">
          <i class='bx bx-grid-alt icon'></i>
          <span class="text">Dashboard</span>
        </a>
        <a href="{% url 'notes:favourites' %}" class="sidebar__link">
          <i class='bx bx-heart icon'></i>
          <span class="text">Favourites</span>
        </a>
        <a href="{% url 'notes:profile' %}" class="sidebar__link">
          <i class='bx bx-user-circle icon'></i>
          <span class="text">Profile</span>
        </a>


      </div>
      <div class="sidebar__bottom">
        <a href="{% url 'notes:logout' %}" class="sidebar__link">
          <i class='logout bx bx-log-out icon'></i>
          <span class="text">Logout</span>
        </a>
      </div>
    </nav>

    <div class="body">
      <header id="header">
        <div class="custom-container">
          <nav class="navbar">
            <div>
              <i class='bx bx-menu icon' id="toggle-btn"></i>
            </div>

            <div>
              <a href="{% url 'notes:add' %}" class="btn btn-success">
                Add A Note
              </a>

              <a class="avatar__section" href="{% url 'notes:profile' %}">
                <img src="{{ user.profile.image.url }}" alt="avatar" class="avatar">
                <div class="right">
                  <span class="username">{{ user.username }}</span>
                  <small class="text-muted">{{ user.email|truncatechars:15 }}</small>
                </div>
              </a>
            </div>
          </nav>
        </div>
      </header>

      <main id="main">
        <div class="mt-3 custom-container">
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% block content %}
          {% endblock %}
        </div>
      </main>
    </div>


  </div>
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  <script>
    $(document).ready(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });
  </script>

  {% block script %} {% endblock %}
</body>

</html>

notes/templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
  <link rel="icon" href="{% static 'favicon.png' %}" sizes="16x16" type="image/png" />
  {% block title %} {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

  <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css"/>
</head>
<body class="auth__body">
  
  <main id="main">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      
      {% block content %}
      {% endblock %}
    </div>
  </main>
  
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  {% block script %} {% endblock %}
</body>
</html>

notes/templates/index.html
{% extends 'base_auth.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  <title>NotesApp</title>
{% endblock %}

{% block content %}
  <div class="auth--form index-page">
      <h1>
        <img src="{% static 'favicon.png' %}" alt="">
        NotesApp</h1>
      <p class="text-muted">A place for students to share & save their priceless notes...</p>
      <div class="buttons">
          <a href="{% url 'notes:login' %}" class="btn btn-primary">Login</a>
          <a href="{% url 'notes:signup' %}" class="btn btn-success">Signup</a>
      </div>
  </div>
{% endblock %}